
json = [
	'{
		"name" : "Arrowhead",
		"petals" : 3,
		"prop1" : "aquatic",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://farm1.static.flickr.com/88/227697921_646888a430.jpg",
		"colour" : "white",
		"colour2" : "yellow",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Trillium",
		"petals" : 3,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/0/0c/White_Trillium_Trillium_grandiflorum_Flower_2613px.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bluets",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.jeffpippen.com/plants/bluets050406-2466facez.jpg",
		"colour" : "white",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Anemone",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/anemone.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bloodroot",
		"petals" : 10,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://www.prairiemoon.com/images/P/Sanguinaria%20canadensis%20(Bloodroot).jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bindweed",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.toronto-wildlife.com/images/bindweed_field_1sh25_081409_640x480.jpg",
		"colour" : "white",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Turtlehead",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://amc-nh.org/resources/guides/wildflowers/images/Chelone%20glabra_White%20Turtlehead_blossom_1_NH_20120721_Beth%20Zimmer_Turtlehead%2003.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "White Sweet Clover",
		"petals" : 0,
		"prop1" : "pea",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://sites.ipfw.edu/native-trees/images/Clover,%20Sweet,%20White,%20Flower.JPG",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Queen Anne\'s Lace",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.field-notebook.com/wp-content/uploads/2010/07/Queen-Annes-Lace11.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bunchberry",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.northcountrypublicradio.org/news/images/bunchberry_375.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bedstraw",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://toronto-wildlife.com/images/bedstraw_bluntleaf_1sh25_070110_640x480.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cowcress",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/cowcress.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Dame\'s Rocket",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://wiseacre-gardens.com/plants/wildflower/dames-rocket-lavender.jpg",
		"colour" : "white",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Garlic Mustard",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/9/90/Garlic_Mustard_close_800.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cut Leaf Toothwort",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.sierrapotomac.org/W_Needham/Pictures/CutLeafToothwort_050417.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cheeses (Common Mallow)",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.aphotoflora.com/images/malvaceae/malva_neglecta_dwarf_mallow_flower_15-08-06.jpg",
		"colour" : "white",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Sandwort",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofireland.net/image_uploads/flowers/Sandwort-Spring-2.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Strawberry",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://c2.staticflickr.com/8/7407/11869678935_6a18ed378b_h.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Labrador Tea",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.sitkanature.org/1000species/wp-content/uploads/2007/06/06-12ledum.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Chickweed",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/chickweed1.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bladder Campion",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/bladdercampion3.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Evening Lychnis",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/eveninglychnis5.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "White Avens",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.illinoiswildflowers.info/savanna/photos/white_avens1.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bouncing Bet (Soapwort)",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/bouncingbet1.jpg",
		"colour" : "white",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Saxifrage",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/d/d4/Micranthes_virginiensis_-_Virginia_Saxifrage_2.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Musk Mallow",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/muskmallow2.jpg",
		"colour" : "white",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "White Water Buttercup",
		"petals" : 5,
		"prop1" : "aquatic",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.cloudbait.com/gwf/img/(0wh)IM2_00863.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Grass of Parnassus",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/grassofparnassus1.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Ox-eyed Daisy",
		"petals" : 10,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/daisy2.jpg",
		"colour" : "white",
		"colour2" : "yellow",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Mayapple",
		"petals" : 6,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://blog.cranesmill.org/wp-content/uploads/2013/05/Mayapple-Flower.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Starflower",
		"petals" : 10,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/starflower1.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "False Soloman\'s Seal",
		"petals" : 10,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.illinoiswildflowers.info/savanna/photos/starry_solomon2.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Hepatica",
		"petals" : 6,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/9/9b/Hepatica_nobilis_plant.JPG",
		"colour" : "white",
		"colour2" : "blue",
		"colour3" : "red",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Cucmber",
		"petals" : 10,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.laspilitas.com/images/grid24_24/9767/images/plants/marah/marah-fabaceus.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Fragrant Water Lily",
		"petals" : 0,
		"prop1" : "aquatic",
		"prop2" : "other",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/fragrantwaterlily3.jpg",
		"colour" : "white",
		"colour2" : "yellow",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Calla (Water Arum)",
		"petals" : 0,
		"prop1" : "aquatic",
		"prop2" : "other",
		"prop3" : "bell",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/0/09/Calla_palustris_(Vosges).JPG",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Speedwell",
		"petals" : 4,
		"prop1" : "aquatic",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://bruxellanatura.files.wordpress.com/2012/06/veronica-anagalis-aquatica.jpg",
		"colour" : "white",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Foxglove",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/foxglovebeardtongue2.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Miterwort",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://blog.cwf-fcf.org/wp-content/uploads/2014/05/mitrewort-640px.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Showy Lady\'s Slipper",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://ontfin.com/Word/wp-content/uploads/2008/06/showy_ladys_slipper.jpg",
		"colour" : "white",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cow Parsnip",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/cowparsnip.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pussy Toes",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/pussytoes4.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Yarrow",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/yarrow1.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Boneset",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wqed.org/birdblog/wp-content/uploads/2010/08/flowers_boneset_rsz2_ct-532x400.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Angelica (Alexanders)",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.plantsystematics.org/users/kcn2/toupload86/Angelica1.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Leek",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/wildleek.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Catnip",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://newfs.s3.amazonaws.com/taxon-images-1000s1000/Lamiaceae/nepeta-cataria-fl-ahaines-a.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pearly Everlasting",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/pearlyeverlasting1.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Sarsaparilla",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://newfs.s3.amazonaws.com/taxon-images-1000s1000/Apiaceae/aralia-nudicaulis-fl-ahaines-e.jpg",
		"colour" : "white",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Evening Primrose",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/eveningprimrose1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Black Mustard",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/mustard.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wintercress",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://minnesotaseasons.com/Plants/Large/W/winter_cress_06.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Calendine",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/celandine1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Yellow Avens",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/yellowavens.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wood Sorel",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/yellowwoodsorel3.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Yellow Violet",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://farm4.staticflickr.com/3598/3445201055_f7e5a7774e.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cinquefoil ",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/cingfoil_rough_fruited1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Silverweed",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildcardwalks.co.uk/images/SILVERWEED-03.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Marsh Merigold",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/marshmarigold7.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Mossy Stonecrop",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/mossystonecrop1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Barren Strawberry",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/barrenstrawberry1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Fringed Loosestrife",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://delawarewildflowers.org/images/lysimachia_ciliata.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "St John\'s Wort",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/stjohnswort1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Kidneyleaf Buttercup",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/kidneybuttercup1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Garden Loosestrife",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/gardenloosestrifewild2.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Shrubby Cinquefoil",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://ebethradecic.files.wordpress.com/2012/08/shrubby-cinquefoil.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bulbous Buttercup",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.aphotoflora.com/images/ranunculaceae/ranunculus_bulbosus_bulbous_buttercup_00_flower_16-05-04.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Swamp Buttercup",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/swampbuttercup1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Moneywort",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/moneywort3.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Lance Leaf Loosestrife",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.perverdonk.com/wild%20flowers/Primrose%20Family/Lanceleaf%20Loosestrife/201006121401260%20%20Lanceleaf%20Loosestrife%20(Lysimachia%20lanceolata)%20-%20Bald%20Mountain%20RA,%20Oakland%20Co.JPG",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Early Buttercup",
		"petals" : 10,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/earlybuttercup.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Lesser Cellandine",
		"petals" : 10,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://wildflowerfinder.org.uk/Flowers/C/Celandine(Lesser)/Celandine(Lesser)_2005_03_26_Brinscal_circ_037.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Swamp Candles",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/swampcandles1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Clammy Ground Cherry",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/clammygroundcherry1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Ragwort",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/ragwort.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Stinking Mayweed Chamomile",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/chamomile1.jpg",
		"colour" : "yellow",
		"colour2" : "white",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Black Eyed Susan",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/c/c2/Blackeyed_Susan_1.JPG",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Coreopsis",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/coreopsis3.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Sunflower",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/tallsunflower1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Elacampane",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/elecampane1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cup Plant",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/6/62/Silphium_perfoliatum_L._(8073308908).jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Dandelion",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/4/4f/DandelionFlower.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Dwarf Dandelion",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/dwarfdandelion1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Sow Thistle ",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/sowthistle1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bur Marigold",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.illinoiswildflowers.info/wetland/photos/bur_marigold1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Goat\'s Beard",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/goatsbeard.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Coltsfoot",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/coltsfoot5.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "King Devil",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/kingdevil2.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bullhead Lily",
		"petals" : 0,
		"prop1" : "aquatic",
		"prop2" : "other",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/bullheadlily.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Yellow Iris",
		"petals" : 0,
		"prop1" : "aquatic",
		"prop2" : "orchid",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/yellow_iris2.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bladderwort",
		"petals" : 0,
		"prop1" : "aquatic",
		"prop2" : "lipped",
		"prop3" : "",
		"images" : "https://www.perverdonk.com/Wild%20Flowers/Bladderwort/201006041115210%20Common%20Bladderwort%20(Utricularia%20vulgaris)%20-%20Misery%20Bay%20NP,%20Manitoulin%20Island.JPG",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Clintonia",
		"petals" : 6,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/clintonia1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bellwort",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://gardeninggab.files.wordpress.com/2008/05/bellwort.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Trout Lily",
		"petals" : 6,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/troutlily7.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Canada Lily (Yellow Wild Lily)",
		"petals" : 6,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/canadalily1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pale Touch-Me-Not",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://bobklips.com/bobs_website/Impatiens-pallida-flower.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Carolina Jasmine",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/carolinajasmine.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Yellow Lady\'s Slipper",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.ontariowildflower.com/images/small_yellow_lady\'s-slipper_flower.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Small Yellow Lady\'s Slipper",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/smallyellowladysslipper4.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Toadflax (Butter & Eggs)",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/toadflax1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Yellow Sweet Clover",
		"petals" : 0,
		"prop1" : "pea",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://minnesotaseasons.com/Plants/Large/Y/yellow_sweet_clover_03.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Birdfoot Trefoil",
		"petals" : 0,
		"prop1" : "pea",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/birdfoot6.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Hop Clover",
		"petals" : 0,
		"prop1" : "pea",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/hopclover4.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Goldenrod",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/goldenrod.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Parsnip",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/wildparsnip2.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Leafy Spurge",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/spurge1.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Tansy",
		"petals" : 0,
		"prop1" : "rayless",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/tansy2.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pineappleweed",
		"petals" : 0,
		"prop1" : "rayless",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/pineappleweed.jpg",
		"colour" : "yellow",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Violet",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/5/56/Violaceae_-_Viola_bertolonii-4.JPG",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Forget-Me-Not",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/forgetmenots.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Flax",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/flax3.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Blue Phlox",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/phlox1.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Periwinkle ",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.gardeningknowhow.com/wp-content/uploads/2011/06/periwinkle.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Blue Eyed Grass",
		"petals" : 6,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.calflora.net/bloomingplants/images/blueeyedgrass8.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Siberian Squill",
		"petals" : 6,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/0/05/Scilla_siberica_Oulu_01.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Chicory",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/chicory4.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "New England Aster",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/newenglandaster.jpg",
		"colour" : "blue",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bergamot",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/bergamot3.jpg",
		"colour" : "blue",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Blueflag",
		"petals" : 0,
		"prop1" : "aquatic",
		"prop2" : "orchid",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/blueflag.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Creeping Bellflower",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/creepingbellflower3.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Harebell",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/harebell5.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Viper\'s Bugloss (Blueweed)",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/bugloss2.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Closed Gentian",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/gentian3.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Nightshade",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/nightshade2.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pickerelweed",
		"petals" : 0,
		"prop1" : "aquatic",
		"prop2" : "other",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/pickerelweed2.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Alfalfa",
		"petals" : 0,
		"prop1" : "pea",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/alfalfa4.jpg",
		"colour" : "blue",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cow Vetch",
		"petals" : 0,
		"prop1" : "pea",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://axiebreen.com/watchingforwildflowers/wp-content/uploads/2013/05/DSC_0013-1024x656.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Monkey Flower",
		"petals" : 0,
		"prop1" : "lipped",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://shop.sweetknowleaquatics.co.uk/WebRoot/Namesco/Shops/950007385/49A7/BA63/13DE/350B/B6D8/3EC1/CD18/06CB/mimulus_0020_ringens.JPG",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Ground Ivy",
		"petals" : 0,
		"prop1" : "lipped",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/gill7.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bugle",
		"petals" : 0,
		"prop1" : "lipped",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/bugle1.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Heal All",
		"petals" : 0,
		"prop1" : "lipped",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/healall1.jpg",
		"colour" : "blue",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Common Skullcap",
		"petals" : 0,
		"prop1" : "lipped",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://7song.com/photos/437/191/Scutellaria-galericulata-(epilobiifolia)-Marsh-skullcap.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Greater Lobelia",
		"petals" : 0,
		"prop1" : "lipped",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/greaterlobelia7.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Blue Vervain",
		"petals" : 0,
		"prop1" : "spiked",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/bluevervain1.jpg",
		"colour" : "blue",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Globe Thistle",
		"petals" : 0,
		"prop1" : "spiked",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/globethistle1.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Blazing Star",
		"petals" : 0,
		"prop1" : "spiked",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://www.prairiemoon.com/images/D/Liatris-spicata-Marsh-Blazing-Star-flower.jpg",
		"colour" : "blue",
		"colour2" : "red",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Hoary Vervain",
		"petals" : 5,
		"prop1" : "spiked",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.biosurvey.ou.edu/okwild/images/horvervain.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Lupins",
		"petals" : 0,
		"prop1" : "spiked",
		"prop2" : "pea",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/lupins.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Henbit",
		"petals" : 0,
		"prop1" : "spiked",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/henbit1.jpg",
		"colour" : "blue",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Orange Hawkweed",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/hawkweed5.jpg",
		"colour" : "orange",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Spotted Touch-Me-Not",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://delawarewildflowers.org/images/impatiens_capensis.jpg",
		"colour" : "orange",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Day Lily",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/daylily5.jpg",
		"colour" : "orange",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Butterflyweed",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/butterflyweed2.jpg",
		"colour" : "orange",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Red Trillium",
		"petals" : 3,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.delawarewildflowers.org/images/trillium_erectum.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Hairy Herb Willow",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/hairyherbwillow4.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Fireweed",
		"petals" : 4,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/fireweed3.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pasture Rose",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.missouriplants.com/Pinkalt/Rosa_carolina_flower.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Geranium",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/geranium1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Purple Flowering Raspberry",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/purplefloweringraspberry3.jpg",
		"colour" : "red",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Scarlett Lychnis",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/scarletlychnis.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Scarlett Pimpernel",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/b/b8/Anagallis_arvensis_2.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Herb Robert",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/herbrobert2.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Deptford Pink",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/deptfordpink4.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Garden Phlox",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/gardenphlox1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pitcher Plant",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/pitcherplant3sss.jpg",
		"colour" : "red",
		"colour2" : "green",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Sheep Laurel",
		"petals" : 5,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://deelish.ie/wp-content/uploads/2012/04/kalmia-angustifolia-rubra.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Purple Loosestrife ",
		"petals" : 6,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/purpleloosestrife3.jpg",
		"colour" : "red",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Flowering Rush",
		"petals" : 6,
		"prop1" : "",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/floweringrush1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Purple Coneflower",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://upload.wikimedia.org/wikipedia/commons/8/80/CH_Echinacea_purpurea.jpg",
		"colour" : "red",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Fleabane",
		"petals" : 10,
		"prop1" : "daisy",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/fleabane1.jpg",
		"colour" : "red",
		"colour2" : "blue",
		"colour3" : "white",
		"scientific" : ""
	}',
	'{
		"name" : "False Dragonhead",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/falsedragonhead.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Columbine",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/columbine.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cardinal Flower",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/cardinal7.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Four O\'Clocks",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://www.prairiemoon.com/images/D/PM%20Mirabilis-nyctaginea_7209%20(2).jpg",
		"colour" : "red",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Indian Touch-Me-Not",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/indiantouchmenot1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Motherwort",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://caliban.mpiz-koeln.mpg.de/~stueber/mavica/high/4500/04049.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Hairy Beardtongue",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.mywildflowers.com/photos/2011/ph21.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cornfrey",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/comfrey4.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Trumpet Honeysuckle",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/trumpethoneysuckle1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Dogbane",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.ontariowildflower.com/images/dogbanefl.jpg",
		"colour" : "red",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Germander",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/germander1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Hound\'s Tongue",
		"petals" : 0,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/houndstongue5.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pink Pyrola",
		"petals" : 5,
		"prop1" : "bell",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.ontariowildflower.com/images/pink_pyrola_flower.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Gay Wings",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/polygala2.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Helleborine",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.botany.wisc.edu/images/Orchids/full/epipactis_detail.jpg",
		"colour" : "red",
		"colour2" : "green",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Calopogon (Grass Pink)",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://newfs.s3.amazonaws.com/taxon-images-1000s1000/Orchidaceae/calopogon-tuberosus-fl-ahaines-a.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Everlasting Pea",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "pea",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/everlastingpea1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Crown Vetch",
		"petals" : 0,
		"prop1" : "pea",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wiseacre-gardens.com/plants/wildflower/vetch_crown.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Milkweed",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://florapittsburghensis.files.wordpress.com/2011/06/asclepias-syriaca-2011-06-23-zelienople-01.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Joe-Pye Weed",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://pardonmygarden.files.wordpress.com/2013/07/garden-07-30-13-082.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Swamp Loosestrife ",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.illinoiswildflowers.info/wetland/photos/sw_lstrife1.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Burdock",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "spiked",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/burdock.jpg",
		"colour" : "red",
		"colour2" : "blue",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Basil",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/basil3.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Canada Thistle",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "spiked",
		"prop3" : "",
		"images" : "http://oregonstate.edu/dept/nursery-weeds/feature_articles/thistles/ct_flower_750.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Knapweed",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/knapweed2.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Bee Balm",
		"petals" : 0,
		"prop1" : "other",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.fs.fed.us/wildflowers/regions/eastern/HighlandScenicHighway/images/scarlet_beebalm_lg.jpg",
		"colour" : "red",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Jack-In-The-Pulpit",
		"petals" : 0,
		"prop1" : "hooded",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/jackinthepulpit.jpg",
		"colour" : "green",
		"colour2" : "brown",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Northern Green Orchid",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://m2.i.pbase.com/o6/01/617601/1/135837652.oZkr4coN.GreenBogOrchid061811.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Coralroot",
		"petals" : 0,
		"prop1" : "orchid",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/coralroot.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Horsetail",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/horsetail1.jpg",
		"colour" : "green",
		"colour2" : "brown",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Green Amaranth",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "https://www.osborneseed.com/uploads/products/4432amaranth__green_tails_08_08_11.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Curled Dock",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.survivalworld.com/images/plants-images/north_american/curly_dock_photo_2.gif",
		"colour" : "brown",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Cattail (Bullrush)",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.gardeningknowhow.com/wp-content/uploads/2012/04/cattails.jpg",
		"colour" : "brown",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Mugwort",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/mugwort2.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "English Plantain",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/englishplantain.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Wild Asparagus",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://newfs.s3.amazonaws.com/taxon-images-1000s1000/Asparagaceae/asparagus-officinalis-fl-ahaines-b.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pale Swallow Wort",
		"petals" : 5,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/paleswallowwort2.jpg",
		"colour" : "brown",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Hairy Wood Rush",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/hairywoodrush1.jpg",
		"colour" : "green",
		"colour2" : "brown",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Horseweed",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/horseweed.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Pale Smartweed",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://www.wildflowersofontario.ca/palesmartweed2.jpg",
		"colour" : "brown",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}',
	'{
		"name" : "Fiddlehead",
		"petals" : 0,
		"prop1" : "clustered",
		"prop2" : "",
		"prop3" : "",
		"images" : "http://foragerchef.com/wp-content/uploads/2013/03/Fiddleheads-405x400.jpg",
		"colour" : "green",
		"colour2" : "",
		"colour3" : "",
		"scientific" : ""
	}'
]

json.each do |flower|
    newflow = Flower.new
    attributes = JSON.parse(flower)
    newflow.assign_attributes(attributes)
    newflow.save
end
	


